version: "3"
services:
       frontend:
          container_name: frontend
          image: frontnew/frontend
          build:
           context: ./my-react
           dockerfile: Dockerfile
          ports:
           - 3006:3006

       backend:
          container_name: backend
          image: backnew/backend
          build:
            context: ./backend
            dockerfile: Dockerfile
          ports:
           - 8088:8088  
          
          

 
  

